<h1 align="center"><b>Modelación Financiera I</b></h1>
<h1 align="center"><b> Módulo 3, parte 1 </b></h1>
<h1 align="center"><b> Computación numérica </b></h1>

*** 

***Docente:*** Santiago Rúa Pérez, PhD.

***e-mail:*** srua@udemedellin.edu.co

***Herramienta:*** [Jupyter Notebook](http://jupyter.org/)

***Kernel:*** Python 3.7

***MEDELLÍN - COLOMBIA***

***2022***

***

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item">
    <li><span><a href="#Introducci%C3%B3n" data-toc-modified-id="Introducci%C3%B3n-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introducción</a></span></li>
    <li><span><a href="#Introducci%C3%B3n-a-numpy" data-toc-modified-id="Introducci%C3%B3n-a-numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Introducción a numpy</a></span></li>
    <div class="toc"><ul class="toc-item">
        <li><span><a href="#Entendiendo-los-tipos-de-datos-en-Python" data-toc-modified-id="Entendiendo-los-tipos-de-datos en-Python-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Entendiendo los tipos de datos en Python</a></span></li>
        <li><span><a href="#Una-lista-en-Python-es-mas-que-una-lista" data-toc-modified-id="Una-lista-en-Python-es-mas-que-una-lista-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Una lista en Python es mas que una lista</a></span></li>
        <li><span><a href="#Creando-array-de-listas" data-toc-modified-id="Creando-array-de-listas-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Creando array de listas</a></span></li>
        <li><span><a href="#Creando-arrays-desde-cero" data-toc-modified-id="Creando-arrays-desde-cero-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Creando arrays desde cero</a></span></li>
        <li><span><a href="#Atributos-de-los-numpy-arrays" data-toc-modified-id="Atributos-de-los-numpy-arrays-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Atributos de los numpy arrays</a></span></li>
        <li><span><a href="#Indexing-y-Slicing" data-toc-modified-id="Indexing-y-Slicing-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Indexing y Slicing</a></span></li>
        <li><span><a href="#Reshaping" data-toc-modified-id="Reshaping-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Reshaping</a></span></li>
        <li><span><a href="#Concatenaci%C3%B3n-y-divisi%C3%B3n-de-arrays" data-toc-modified-id="Concatenaci%C3%B3n-y-divisi%C3%B3n-de-arrays-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Concatenación y división de arrays</a></span></li>
    </ul></div>
    <li><span><a href="#Computaci%C3%B3n-y-agregaciones" data-toc-modified-id="Computaci%C3%B3n-y-agregaciones-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Computación y agregaciones</a></span></li>
    <div class="toc"><ul class="toc-item">
        <li><span><a href="#Introducci%C3%B3n-a-las-funciones-universales" data-toc-modified-id="Introducci%C3%B3n-a-las-funciones-universales-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Introducción a las funciones universales</a></span></li>
    </ul></div>
    </ul></div>

## Introducción

- Por el momento solo se ha trabajado con números individuales o con conjunto de datos arreglados. Este conjunto de datos organizados bajo un mismo nombre se ha trabajado desde listas, tuplas y diccionarios. 

- Estas estructuras sin embargo no son eficientes cuando se tratan de realizar operaciones matemáticas. 

- Lo anterior generar la necesidad de crear un tipo de datos que sean eficientes cuando se esten realizando computos matemáticos. Para solucionar este problema se utiliza la libreria `numpy`

## Introducción a numpy

**Qué es numpy?**
- Una biblioteca para `Python`: `ndarray` + `ufunc`

- Los arrays multidimensionales (`ndarray`) nos permiten almacenar datos de manera estructurada

- Las funciones universales (`ufunc`) nos permiten operar con esos datos de manera eficiente

`Python` está organizado en módulos, que son archivos con extensión `*.py` que contienen funciones, variables y otros objetos, y paquetes, que son conjuntos de módulos. 


Cuando queremos utilizar objetos que están definidos en un módulo tenemos que *importarlo*, y una vez que lo hemos hecho podemos usar el operador "`.`" para ir descendiendo en la jerarquía de paquetes y acceder al objeto que necesitamos.

In [1]:
import numpy as np
np.random

<module 'numpy.random' from 'C:\\Users\\srua\\Anaconda3\\envs\\MLFinancePy3_7\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [2]:
from numpy import random

Para encontrar ayuda sobre cierto tema podemos usar la función `lookfor`:

In [3]:
np.lookfor("random")

Search results for 'random'
---------------------------
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.matlib.randn
    Return a random matrix with data from the "standard normal" distribution.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.prod
    Return the product of array elements over a given axis.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.stack
    Join a sequence of arrays along a new axis.
numpy.fliplr
    Flip array in the left/right direction.
numpy.flipud
    Flip array in the up/down direction.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.convolve
    Returns the discrete, linear convolution of two one-dimensional sequences.
numpy.histogram
    Compute the histogram of a set of data.
numpy.empty_like
    Return a new array with the same

### Entendiendo los tipos de datos en Python

La ciencia y la computación efectivas basadas en datos requieren comprender cómo se almacenan y manipulan los datos. Esta sección describe y contrasta cómo se manejan las matrices de datos en el propio lenguaje Python y cómo NumPy mejora esto.

Los usuarios de Python a menudo se sienten atraídos por su facilidad de uso, una de las cuales es la escritura dinámica. Mientras que un lenguaje de tipo estático como C o Java requiere que cada variable se declare explícitamente, un lenguaje de tipo dinámico como Python omite esta especificación. Por ejemplo, en C puede especificar una operación en particular de la siguiente manera

```c
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

Mientras que en Python se tiene la operación equivalente

```python
# Python code
result = 0
for i in range(100):
    result += i
```

La principal diferencia es el tipo de variable declarada explícitamente. Eso significa que en python se puede asignar cualquier valor a la variables.

```python
# Python code
x = 4
x = "four"
```

Si hicieramos lo mismo con C o javascript entonces se genera un error de compilación. 



### Una lista en Python es mas que una lista

Ahora se procede a analizar que pasa cuando se crea una lista en Python. Recuerde que las listas en Python son objetos mutables 

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

También se puede crear una lista de cadenas

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

La fleixibilidad de las listas viene con un costo: cada elemento de la lista debe tener su propia informacion de referencia. En el caso donde todos los datos son lo mismos, se tiene información redundante. Se puede realizar una comparación de la creación de un numpy array y una lista conteniendo la misma información

![ArrayList](img/array_vs_list.png)

Notese que tienen los mismos datos pero las listas son mas ineficientes cuando contienen el mismo tipo de datos. Para mejorar lo anterior Python cuenta con la libreria `array` la cual sirve para mejorar la eficiencia en el almacenado de los datos. Sin embargo, la libreria `numpy` le adiciona operaciones a esos datos de forma eficiente.

### Creando array de listas

Se puede utiliza la función `np.array` para crear array de una lista

In [9]:
import numpy as np
a = np.array([1,2,5,3])
print(a)
print(type(a))

[1 2 5 3]
<class 'numpy.ndarray'>


Recuerde que los datos deben ser del mismo tipo, o python hace el casting si es posible. Tambien se puede especificar de forma directa


In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Tambien se puede trabajar array multidimensionales

In [13]:
a_list = [range(i, i + 3) for i in [2, 4, 6]]
print(a_list)
a_numpy = np.array(a_list)
print(a_numpy)

[range(2, 5), range(4, 7), range(6, 9)]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


### Creando arrays desde cero

Se pueden crear array desde cero utilizando métodos propios de la libreria. A continuación algunos métodos:

- `np.zeros(dim)`: crea un numpy array de ceros de acuerdo a la dimension especificada

- `np.ones(dim)`: crea un numpy array de unos de acuerdo a la dimensión especificada

- `np.full(dim, number)`: crea un numpy array de un número especificado de acuerdo a la dimensión selecionada

- `np.linspace(start,stop,n)`: crea un numpy array desde `start` hasta el `stop` con `n` número igualmente espaciados

- `np.random.random(dim)`: crea un numpy array de dimensión `dim` con número aleatorios uniformemente distribuidos

- `np.eye(dim)`: crea una matriz identidad de dimensión `dim`

In [15]:
a = np.zeros(10, dtype=int)
print(a)
print(type(a))

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [16]:
a = np.ones((3, 5), dtype=float)
print(a)
print(type(a))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [17]:
a = np.full((3, 5), 3.14)
print(a)
print(type(a))

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
<class 'numpy.ndarray'>


In [18]:
a = np.arange(0, 20, 2)
print(a)
print(type(a))

[ 0  2  4  6  8 10 12 14 16 18]
<class 'numpy.ndarray'>


In [19]:
a = np.linspace(0, 1, 5)
print(a)
print(type(a))

[0.   0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>


In [21]:
a = np.random.random((3, 3))
print(a)
print(type(a))

[[0.62660592 0.16599201 0.89690686]
 [0.70473871 0.75698946 0.29659111]
 [0.2881069  0.34731606 0.37435606]]
<class 'numpy.ndarray'>


In [22]:
a = np.eye(3)
print(a)
print(type(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

### Atributos de los numpy arrays

Es importante revisar algunos de los atributos que presenta la clase `numpy`. Cada array tiene tres atributos principales relacionados con el tamaño: ``ndim`` número de dimensiones, ``shape`` el tamaño de cada dimensión, and ``size`` el tamaño total del array. Para entender lo anterior se procede a crear tres arrays

In [25]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Otros tres atributos interesantes con: `dtype` el cual indica el tipo de dato, `itemize` da información del tamaño ocupado en memoria por cada dato, y `nbytes` el tamaño total en bytes.

In [26]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


### Indexing y Slicing

La indexación y el slicing para los numpy array se realiza de la misma forma que se realizaba con las listas de python

In [27]:
x1[0]

5

In [28]:
x1[-1]

9

In [29]:
x2[2, 0]

1

In [30]:
print(x2)
x2[0, 0] = 12
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Recuerde que a diferencia de las listas en python, los numpy array tiene un dato fijo. Lo anterior significa que python intetará almacenar el nuevo valor haciendo un casting o saldrá un error. El slicing sigue el mismo patron

``` python
x[start:stop:step]
```



In [34]:
x1[2::2]

array([3, 7])

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[:5]

array([0, 1, 2, 3, 4])

In [36]:
x[::2]

array([0, 2, 4, 6, 8])

In [38]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
x[5::-2]

array([5, 3, 1])

In [44]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [45]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

***Nota**: recuerde que cuando hace asignación, para los numpy array equivale a crea un alias y no un copia en memoria. Si quiere una copia totalmente diferente recuerde utilizar el metodo `numpy.copy`

### Reshaping

Numpy nos posibilita también realizar cambio de dimensiones en los arrays. La forma más flexible y fácil de realizar esto es mediante la función `reshape`. Por ejemplo, si se desea poner un vector fila de 9 posiciones en un matriz de 3x3, entonces

In [46]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Es importante aclarar que el tamaño nuevo al que se quiere ajustar deben tener el mismo tamaño. Cuando sea posible el método reshape usará una no-copia del array original, pero no siempre es el caso. 

In [51]:
x = np.array([1, 2, 3])
print(x.shape)
print(x.reshape((1, 3)).shape)

(3,)
(1, 3)


In [53]:
x[np.newaxis, :].shape

(1, 3)

In [54]:
x.reshape((3, 1)).shape

(3, 1)

In [55]:
x[:, np.newaxis].shape

(3, 1)

### Concatenación y división de arrays

Es posible realizar concatenación o división de arrays en multiples arrays. 

- Para concatenar se pueden utilizar las rutinas tales como: `np.concatenate`, `np.vstack`, `np.hstack`

- Para dividirlos se pueden utilizar las rutinas tales como: `np.split`, `np.hsplit`, `np.vsplit`

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [57]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [58]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# Se puede seleccionar la dimensión sobre el que se quiere concatenar
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
# Te posibilita trabajar con diferentes dimensiones
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Realizando las operaciones opuestas a concatenación para dividr los array entonces se tiene que:

In [64]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [65]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [67]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computación y agregaciones

Hasta el momento solo se ha discutido o mostrado las nociones básicas de la libreria. Sin embargo, a continuación se mostrará la potencia de la libreria y porque se ha convertido en el estándar para la ciencia de datos. 

Las operaciones con `numpy` pueden ser muy rápidas o lentas dependiendo de la implementación. La clave para que sean rápidos es que se utilicen la forma vectorizada de las operaciones y evitar a toda costa el uso de loops.

Un mal ejemplo de utilización de python es por ejemplo cuando se desea recorrer un vector para realizar una operación sobre el mismo. Por ejemplo, supongamos que se desea encontrar el inverso de un vector

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

Para una persona que conozca otros lenguajes de programación, esta implementación puede ser la más lógica. Sin embargo, no se está aprovechando la utilizanción de la libreria. Podemos obtener el tiempo en que se demorar ejecutar la función utilizando la función mágica de IPython ```%timeit```

In [8]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.44 s ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducción a las funciones universales

Para muchas aplicaciones, `numpy` provee una interfaz conveniente para realizar operaciones y compilarlas directamente. Lo anterior se conoce como operaciones vectorizadas. Lo anterior implica que se realiza una operación y se ejecuta elemento a elemento. El objetivo de realizar esto es que la operación se de en la capa de compilación de la libreria para una ejecución más rápida

In [5]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


Recordemos que los resultados utilizando un loop fueron

```python
1.44 s ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Ahora analizando la ejecución de la última instrucción se tiene que

In [9]:
%timeit (1.0 / big_array)

2.95 ms ± 33 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

Es importante entender que las operaciones pueden ser realizadas para arrays de diferentes tamaños. Por ejemplo se tiene las operaciones matemáticas básicas

In [12]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [13]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [14]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

La siguiente tabla muestras las operaciones implementadas en numnpy:

| Operador	    | ufunc    | Descripción                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


In [15]:
x = np.array([-2, -1, 0, 1, 2])
print(abs(x))
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


In [16]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [17]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [18]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [19]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
